version: '3.1'

services:

  db:
    image: postgres
    container_name: polls_container
    restart: always
    environment:
      POSTGRES_PASSWORD: 132565
      POSTGRES_USER: postgres
      POSTGRES_DB: somedb
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
     - "54321:5432"