# Generated by Django 4.0.4 on 2022-06-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfPolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='ChoiceDRF',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionDRF',
        ),
    ]
