# Generated by Django 4.0.4 on 2022-06-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfPolls', '0002_rename_choice_choicedrf_rename_question_questiondrf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondrf',
            old_name='question_text',
            new_name='description',
        ),
    ]
